export const EducationData = [
   '10th Pass',
   '12th Pass',
   'Computer Engineer',
   'Civil Engineer',
   'Designer',
]

export const InterestData = [
    'Cities & places',
    'Bollywood',
    'Cricket',
    'Funny',
    'Jokes',
    'Memes',
    'Interesting',
    'Be amazed',
    'Fails',
    'unexpected',
    'Confession & stories',
    'Ask Reddit',
    'Opinions',
    'Lifehacks',
    'Oddly satisfying',
    'Heartwarming',
    'Animals & awwws',
    'Learn something',
    'Space',
    'History',
    'Languages',
    'Nature',
    'Science',
    'News',
    'Tech',
    'Google',
    'Apple',
    'Gaming',
    'YouTubers',
    'Bussiness',
    'Stock',
    'Crypto',
    'Personal finance',
    'Career',
    'Studying',
    'Family',
    'Movies',
    'TV',
    'Marvel Cinematic Universe',
    'Sport',
    'IPL',
    'Football',
    'Scifi',
    'Fantasy',
    'Fan theories',
    'Game of Thrones',
    'Music',
    'Making music',
    'Hip-hop',
    'Electronic music',
    'K-pop',
    'Indie music',
    'Anime',
    'Anime memes',
    'Books',
    'Writing',
    'Comics',
    'Art',
    'Painting',
    'Drawing',
    'Digital art',
    'Photography',
    'Graphic design',
    'Programming',
    'Pragramming humor',
    'DIY & crafts',
    'DIY electronics',
    'Male fashion',
    'Female fashion',
    'Tattoos',
    'Skincare',
    'Makeup',
    'Hair',
    'Nails',
    'Food',
    'Healthy food',
    'Baking',
    'Easy cooking',
    'Home improvement',
    'Home decoratibng',
    'Gardening',
    'Sustainability',
    'Fitness',
    'Get morivated',
    'Gym',
    'Yoga',
    'Wellness',
    'Running',
    'Weight loss',
    'Outdoors',
    'Travel',
    'Cars & motor vehicles'
]