export const EducationData = [
  '10th Pass',
  '12th Pass',
  'Computer Engineer',
  'Civil Engineer',
  'Designer',
];

export const InterestData = [
  'Cities & Places',
  'Bollywood',
  'Cricket',
  'Funny',
  'Jokes',
  'Memes',
  'Interesting',
  'Be amazed',
  'Fails',
  'unexpected',
  'Confession & Stories',
  'Ask Reddit',
  'Opinions',
  'Life Hacks',
  'Oddly satisfying',
  'Heartwarming',
  'Animals & awwws',
  'Learn something',
  'Space',
  'History',
  'Languages',
  'Nature',
  'Science',
  'News',
  'Tech',
  'Google',
  'Apple',
  'Gaming',
  'YouTubers',
  'Business',
  'Stock',
  'Crypto',
  'Personal finance',
  'Career',
  'Studying',
  'Family',
  'Movies',
  'TV',
  'Marvel Cinematic Universe',
  'Sport',
  'IPL',
  'Football',
  'Sci-Fi',
  'Fantasy',
  'Fan theories',
  'Game of Thrones',
  'Music',
  'Making music',
  'Hip-hop',
  'Electronic music',
  'K-pop',
  'Indie music',
  'Anime',
  'Anime memes',
  'Books',
  'Writing',
  'Comics',
  'Art',
  'Painting',
  'Drawing',
  'Digital art',
  'Photography',
  'Graphic design',
  'Programming',
  'Programming humor',
  'DIY & crafts',
  'DIY electronics',
  'Male fashion',
  'Female fashion',
  'Tattoos',
  'Skincare',
  'Makeup',
  'Hair',
  'Nails',
  'Food',
  'Healthy food',
  'Baking',
  'Easy cooking',
  'Home improvement',
  'Home decorating',
  'Gardening',
  'Sustainability',
  'Fitness',
  'Get motivated',
  'Gym',
  'Yoga',
  'Wellness',
  'Running',
  'Weight loss',
  'Outdoors',
  'Travel',
  'Cars & motor vehicles',
];

export const InterestDataSelector = [
  {labels:'Cities & Places' ,value:'Cities & Places'},
  {labels:'Bollywood' ,value:'Bollywood'},
  {labels:'Cricket' ,value:'Cricket'},
  {labels:'Funny' ,value:'Funny'},
  {labels:'Jokes' ,value:'Jokes'},
  {labels:'Memes' ,value:'Memes'},
  {labels:'Interesting' ,value:'Interesting'},
  {labels:'Be amazed' ,value:'Be amazed'},
  {labels:'Fails' ,value:'Fails'},
  {labels:'unexpected' ,value:'unexpected'},
  {labels:'Confession & Stories' ,value:'Confession & Stories'},
  {labels:'Ask Reddit' ,value:'Ask Reddit'},
  {labels:'Opinions' ,value:'Opinions'},
  {labels:'Life Hacks' ,value:'Life Hacks'},
  {labels:'Oddly satisfying' ,value:'Oddly satisfying'},
  {labels:'Heartwarming' ,value:'Heartwarming'},
  {labels:'Animals & awwws' ,value:'Animals & awwws'},
  {labels:'Learn something' ,value:'Learn something'},
  {labels:'Space' ,value:'Space'},
  {labels:'History' ,value:'History'},
  {labels:'Languages' ,value:'Languages'},
  {labels:'Nature' ,value:'Nature'},
  {labels:'Science' ,value:'Science'},
  {labels:'News' ,value:'News'},
  {labels:'Tech' ,value:'Tech'},
  {labels:'Google' ,value:'Google'},
  {labels:'Apple' ,value:'Apple'},
  {labels:'Gaming' ,value:'Gaming'},
  {labels:'YouTubers' ,value:'YouTubers'},
  {labels:'Business' ,value:'Business'},
  {labels:'Stock' ,value:'Stock'},
  {labels:'Crypto' ,value:'Crypto'},
  {labels:'Personal finance' ,value:'Personal finance'},
  {labels:'Career' ,value:'Career'},
  {labels:'Studying' ,value:'Studying'},
  {labels:'Family' ,value:'Family'},
  {labels:'Movies' ,value:'Movies'},
  {labels:'TV' ,value:'TV'},
  {labels:'Marvel Cinematic Universe' ,value:'Marvel Cinematic Universe'},
  {labels:'Sport' ,value:'Sport'},
  {labels:'IPL' ,value:'IPL'},
  {labels:'Football' ,value:'Football'},
  {labels:'Sci-Fi' ,value:'Sci-Fi'},
  {labels:'Fantasy' ,value:'Fantasy'},
  {labels:'Fan theories' ,value:'Fan theories'},
  {labels:'Game of Thrones' ,value:'Game of Thrones'},
  {labels:'Music' ,value:'Music'},
  {labels:'Making music' ,value:'Making music'},
  {labels:'Hip-hop' ,value:'Hip-hop'},
  {labels:'Electronic music' ,value:'Electronic music'},
  {labels:'K-pop' ,value:'K-pop'},
  {labels:'Indie music' ,value:'Indie music'},
  {labels:'Anime' ,value:'Anime'},
  {labels:'Anime memes' ,value:'Anime memes'},
  {labels:'Books' ,value:'Books'},
  {labels:'Writing' ,value:'Writing'},
  {labels:'Comics' ,value:'Comics'},
  {labels:'Art' ,value:'Art'},
  {labels:'Painting' ,value:'Painting'},
  {labels:'Drawing' ,value:'Drawing'},
  {labels:'Digital art' ,value:'Digital art'},
  {labels:'Photography' ,value:'Photography'},
  {labels:'Graphic design' ,value:'Graphic design'},
  {labels:'Programming' ,value:'Programming'},
  {labels:'Programming humor' ,value:'Programming humor'},
  {labels:'DIY & crafts' ,value:'DIY & crafts'},
  {labels:'DIY electronics' ,value:'DIY electronics'},
  {labels:'Male fashion' ,value:'Male fashion'},
  {labels:'Female fashion' ,value:'Female fashion'},
  {labels:'Tattoos' ,value:'Tattoos'},
  {labels:'Skincare' ,value:'Skincare'},
  {labels:'Makeup' ,value:'Makeup'},
  {labels:'Hair' ,value:'Hair'},
  {labels:'Nails' ,value:'Nails'},
  {labels:'Food' ,value:'Food'},
  {labels:'Healthy food' ,value:'Healthy food'},
  {labels:'Baking' ,value:'Baking'},
  {labels:'Easy cooking' ,value:'Easy cooking'},
  {labels:'Home improvement' ,value:'Home improvement'},
  {labels:'Home decorating' ,value:'Home decorating'},
  {labels:'Gardening' ,value:'Gardening'},
  {labels:'Sustainability' ,value:'Sustainability'},
  {labels:'Fitness' ,value:'Fitness'},
  {labels:'Get motivated' ,value:'Get motivated'},
  {labels:'Gym' ,value:'Gym'},
  {labels:'Yoga' ,value:'Yoga'},
  {labels:'Wellness' ,value:'Wellness'},
  {labels:'Running' ,value:'Running'},
  {labels:'Weight loss' ,value:'Weight loss'},
  {labels:'Outdoors' ,value:'Outdoors'},
  {labels:'Travel' ,value:'Travel'},
  {labels:'Cars & motor vehicles' ,value:'Cars & motor vehicles'},
];
