import {ms, s, ScaledSheet, vs} from 'react-native-size-matters';
import colors from '../../theme/colors/colors';

export default ScaledSheet.create({
  container: {
    flex: 1,
  },
  editIcon: {
    backgroundColor:colors.AppTheme.OtherFirst,
    padding:ms(5),
    borderRadius:ms(15),
    position:'absolute',
    right:0,
    bottom:-2
  },
  profileImage: {
    width: ms(60),
    height: ms(60),
    borderRadius: ms(30),
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.AppTheme.grayShadeAB,
    borderColor: colors.AppTheme.Primary,
  },
  cameraIcon: {
    opacity: 0.8,
  },
  renderViewContainer: {
    flex: 1,
    marginHorizontal: ms(16),
    marginBottom: ms(80),
  },
  usernameTxtStyle: {
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Medium',
  },
  textInputView: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  textInput: {
    borderColor: colors.AppTheme.grayShadeAB,
    borderWidth: ms(1),
    borderRadius: ms(4),
    fontSize: ms(14),
    marginTop: ms(10),
    marginRight: ms(16),
    paddingLeft: ms(16),
    textAlignVertical: 'center',
    height: ms(40),
    width: '100%',
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Medium',
  },
  textInputViewNew: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    backgroundColor: '#FFF',
    width: '100%',
    borderRadius: ms(10),
    height: ms(50),
    marginTop: ms(6),
    fontSize: ms(14),
    paddingHorizontal: ms(12),
    // marginTop: ms(20),
  },
  textInputDropDown: {
    // flex: 1,
    // paddingHorizontal: ms(16),
    // justifyContent: 'center',
    textAlign: 'center',
    padding: 0,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    backgroundColor: '#FFF',
    minHeight: ms(50),
    height: 'auto',
    marginTop: ms(6),
    borderColor: 'transparent',
    borderRadius: ms(10),
  },
  textInputNew: {
    fontSize: ms(14),
    width: '100%',
    paddingHorizontal: ms(12),
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Medium',
  },
  dateViewInput: {
    height: ms(40),
    paddingLeft: ms(16),
    paddingRight: ms(16),
    borderColor: colors.AppTheme.grayShadeAB,
    justifyContent: 'center',
    borderWidth: ms(1),
    borderRadius: ms(4),
    marginTop: ms(10),
  },
  dateText: {
    fontSize: ms(16),
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Medium',
  },
  genderContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: ms(3),
    width: '100%',
    // backgroundColor: 'red',
    // justifyContent: 'space-between',
  },
  genderText: {
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Medium',
    left: ms(-2),
    // marginHorizontal: ms(4),
  },
  aboutTextInput: {
    fontSize: ms(14),
    marginRight: ms(16),
    paddingLeft: ms(16),
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Medium',
  },
  aboutTextInputView: {
    height: ms(100),
    alignItems: 'flex-start',
  },
  interstedItemContainer: {
    marginTop: ms(16),
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  interestItemView: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    borderWidth: 1,
    borderColor: 'transparent',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
    elevation: 2,
    borderRadius: ms(50),
    padding: ms(8),
    paddingHorizontal: ms(10),
    margin: ms(5),
  },
  labelItem: {
    marginHorizontal: ms(5),
    fontSize: ms(14),
    color: colors.AppTheme.Secondary,
  },
  profileContainer: {
    backgroundColor: colors.AppTheme.Secondary,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    flexDirection: 'row',
    marginTop: ms(16),
    marginHorizontal: ms(12),
    borderRadius: ms(10),
    alignItems: 'center',
    flex: 1,
    paddingTop: ms(10),
    paddingBottom: ms(16),
    paddingHorizontal: ms(12),
  },
  profileTitle: {
    fontSize: ms(17),
    fontFamily: 'DMSans-Bold',
    color: colors.AppTheme.Text,
    marginHorizontal: ms(12),
  },
  gender: {
    fontSize: ms(14),
    width: '100%',
    paddingHorizontal: ms(12),
    flex: 1,
    alignItems: 'center',
    marginTop: ms(20),
  },
  containerDropDown: {
    flex: 1,
    padding: ms(16),
    justifyContent: 'center',
  },
  icon: {
    marginRight: ms(5),
  },
  placeholderStyle: {
    fontSize: ms(16),
    color: colors.AppTheme.Text,
  },
  selectedTextStyle: {
    fontSize: ms(16),
    color: colors.AppTheme.Text,
  },
  iconStyle: {
    width: ms(20),
    height: ms(20),
  },
  inputSearchStyle: {
    height: ms(40),
    fontSize: ms(16),
    color: colors.AppTheme.Text,
    borderColor: colors.AppTheme.PlaceholderColor,
  },
  interstedTxtStyle: {
    color: colors.AppTheme.label,
    fontSize: ms(16),
    // fontWeight: 'bold',
  },
  editLogo: {
    paddingLeft: ms(5),
  },

  flexRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  editText: {
    fontSize: ms(16),
    fontFamily: 'DMSans-Bold',
    color: colors.AppTheme.Text,
  },
  textInputBox: {
    marginTop: ms(16),
  },
  textInputLabel: {
    fontSize: ms(14),
    fontFamily: 'DMSans-Bold',
    color: colors.AppTheme.label,
    paddingLeft: ms(6),
  },
  interestMain: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: ms(16),
  },
  ProfilePhotoBottomSheetContainer: {
    backgroundColor: colors.AppTheme.Secondary,
    borderTopEndRadius: ms(15),
    borderTopStartRadius: ms(15),
    width: '100%',
    paddingHorizontal: ms(16),
    paddingVertical: ms(40),
  },
  editProfileText: {
    fontWeight: 'bold',
    color: colors.AppTheme.Text,
    textAlign: 'center',
  },
  editProfileTitle: {
    marginTop: ms(16),
  },
  editProfileTitleText: {
    fontSize: ms(16),
    color: colors.AppTheme.Text,
    fontWeight: '400',
    marginLeft: ms(16),
  },
  bottomCamera: {
    backgroundColor: colors.AppTheme.Primary,
    height: ms(60),
    width: ms(60),
    borderRadius: ms(50),
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
  },
  bottomTouchable: {
    // alignItems:'center',
  },
  btnText: {
    marginTop: ms(4),
    fontSize: ms(16),
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Medium',
  },
  viewPoll: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: ms(16),
    marginBottom: ms(8),
    backgroundColor: colors.AppTheme.Secondary,
    padding: ms(16),
  },
  viewPollText: {
    fontFamily: 'DMSans-Bold',
    color: colors.AppTheme.Text,
    fontSize: ms(16),
  },
  viewPollContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
});
