import {ms, s, ScaledSheet, vs} from 'react-native-size-matters';
import colors from '../../theme/colors/colors';

export default ScaledSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#EFEFEF',
  },
  privateSwitchContainer: {
    flexDirection: 'row',
    marginTop: ms(15),
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  titleTextInput: {
    height: ms(70),
    padding: ms(14),
    marginTop: ms(16),
    paddingHorizontal: ms(20),
    paddingVertical: ms(12),
    borderRadius: ms(10),
    fontSize: ms(20),
    color: 'black',
    textAlignVertical: 'top',
  },
  descriptionContainer: {
    height: ms(100),
    textAlignVertical: 'top',
  },
  optionContainer: {
    marginTop: ms(10),
  },
  optionTextInput: {
    color: colors.AppTheme.Text,
    height: ms(50),
    marginTop: ms(10),
    padding: ms(10),
    fontSize: ms(13),
    borderRadius: ms(10),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    borderWidth: 0,
    backgroundColor: '#fff',
  },
  optionTextInputFirst: {
    marginTop: ms(24),
  },
  closeTextInput: {
    color: colors.AppTheme.Text,
    height: ms(50),
    marginTop: ms(10),
    padding: ms(10),
    fontSize: ms(13),
    borderRadius: ms(10),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    backgroundColor: '#fff',
    borderWidth: 0,
    width: '85%',
  },
  moreOptionTextInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    justifyContent: 'space-between',
  },
  removeOptionView: {
    marginRight: ms(5),
    alignItems: 'center',
  },
  addOptionButton: {
    marginTop: ms(20),
    alignItems: 'center',
  },
  moreOptionTextInput: {
    height: ms(50),
    padding: ms(14),
    marginVertical: ms(8),
    paddingHorizontal: ms(20),
    paddingVertical: ms(12),
    borderColor: '#CCCED2',
    borderWidth: ms(1),
    borderRadius: ms(10),
    fontSize: ms(13),
    color: 'black',
    width: '90%',
  },
  pollTitle: {
    fontSize: ms(18),
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Bold',
    paddingLeft: ms(6),
  },
  pollContain: {
    marginTop: ms(16),
    flexDirection: 'row',
    alignItems: 'center',
  },
  addOptionButtonStyle: {
    alignItems: 'flex-end',
    width: ms(100),
    borderRadius: ms(10),
    flex: 1,
    height: ms(40),
    marginTop: ms(16),
    backgroundColor: 'transparent',
  },
  addOptionText: {
    color: colors.AppTheme.Primary,
    fontSize: ms(16),
    fontFamily: 'DMSans-Bold',
    borderBottomWidth: 1,
    borderBottomColor: colors.AppTheme.Primary,
  },
  selectPollText: {
    fontSize: ms(16),
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Bold',
    marginVertical:ms(10)
  },
  selectPoll: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: ms(10),
  },
  containerCreateFeed: {
    flex: 1,
    padding: ms(16),
    justifyContent: 'center',
  },
  dropdown: {
    height: ms(50),
    borderColor: 'gray',
    borderWidth: ms(0.5),
    borderRadius: ms(8),
    paddingHorizontal: ms(8),
    marginVertical: ms(5),
  },
  icon: {
    marginRight: ms(5),
  },
  placeholderStyle: {
    fontSize: ms(16),
    color: colors.AppTheme.Text,
  },
  selectedTextStyle: {
    fontSize: ms(16),
    color: colors.AppTheme.Text,
  },
  iconStyle: {
    width: ms(20),
    height: ms(20),
  },
  inputSearchStyle: {
    height: ms(40),
    fontSize: ms(16),
  },
  containerRange: {
    flex: 1,
    alignItems: 'stretch',
    justifyContent: 'center',
    marginTop: ms(16),
  },
  voteRangeText: {
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Medium',
    textAlign: 'center',
    fontSize: ms(14),
  },
  uploadImageText: {
    fontSize: ms(16),
    color: colors.AppTheme.Text,
    marginRight: ms(6),
  },
  uploadImageTextMain: {
    marginTop: ms(16),
    alignItems: 'center',
  },
  selectPollMain: {
    flexDirection: 'column',
    alignItems: 'center',
    marginTop: ms(4),
  },
  selectPollContent: {
    backgroundColor: '#fff',
    padding: ms(12),
    margin: ms(12),
    borderRadius: ms(20),
  },
  selectPollTitle: {
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Bold',
    fontSize: ms(16),
    marginTop: ms(8),
  },
  dateViewInput: {
    height: ms(40),
    paddingHorizontal: ms(16),
    justifyContent: 'center',
    borderRadius: ms(4),
    marginTop: ms(10),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    backgroundColor: '#fff',
  },

  pollVoteInput: {
    textAlign: 'center',
    alignContent: 'center',
    backgroundColor: '#fff',
    width: ms(80),
    height: ms(40),
    fontSize: ms(16),
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Medium',
    borderRadius: ms(4),
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  explanationIcon: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  explanationIconMain: {
    width: ms(23),
    height: ms(23),
    borderWidth: ms(1),
    borderRadius: ms(8),
    borderColor: colors.AppTheme.PlaceholderColor,
  },
  explanationMain: {
    // alignItems: 'center',
    // flexDirection: 'row',
    // justifyContent: 'space-between',
    marginTop: ms(16),
  },
  explanationTitle: {
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Bold',
    fontSize: ms(16),
  },
  themeButton: {
    marginTop: ms(40),
  },
  containerDropDown: {
    flex: 1,
    padding: ms(16),
    justifyContent: 'center',
  },
  textInputDropDown: {
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
    backgroundColor: '#FFF',
    height: ms(50),
    marginTop: ms(6),
    borderWidth: 1,
    borderColor: 'transparent',
    borderRadius: ms(10),
  },
  dropdownInputSearchStyle: {
    height: ms(40),
    fontSize: ms(16),
    color: colors.AppTheme.Text,
  },

  genderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: ms(3),
  },
  genderText: {
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Medium',
    marginHorizontal: ms(5),
  },
  dateText: {
    fontSize: ms(16),
    color: colors.AppTheme.Text,
    fontFamily: 'DMSans-Medium',
  },
  toggleSwitch: {
    fontWeight: '700',
    fontSize: ms(16),
    color: colors.AppTheme.Primary,
  },
  explanationButtonMain: {
    flexDirection: 'row',
    alignContent: 'center',
    marginTop: ms(16),
  },
  explanationButton: {
    paddingVertical: ms(10),
    paddingHorizontal: ms(37),
    backgroundColor: colors.AppTheme.OtherSecond,
    marginRight: ms(16),
    borderRadius: ms(6),
  },
  explanationButtonCheck: {
    backgroundColor: colors.AppTheme.Primary,
  },
  explanationButtonText: {
    color: colors.AppTheme.Text,
    fontSize: ms(16),
  },
  explanationButtonTextCheck: {
    color: colors.AppTheme.Secondary,
  },
  svgContainer: {
    borderRadius:ms(20),
    backgroundColor: colors.AppTheme.Secondary,
    padding:ms(12)
  }
});
